# Description: Configuration file for the GazeCapture dataset.
config:
  type: "gaze"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'GazeCapture'
  seed: 42
  train_val_test_split: [0.8, 0.1]
  query_size: 100
  support_size: 9
  gazecapture:
    num_of_ids: 20 # -1 means all ids
    max_per_participant: 25 # 32

# Configuration for the optimizer.
optimizer:
  outer_lr: 0.001 # 1e-3
  inner_lr: 0.00001 # 1e-5
  decay_rate: 0.95

# Training configuration.
training:
  batch_size: 8
  num_outer_steps: 100
  num_inner_steps: 5

# Configuration for the model.
model:
  mode: 'gaze'
  model_weights_fp: null
  encoder_weights_fp: 'autoencoder_2025-03-29-12-30-25'
  input_shape: [128,512,3]
  embedding_size: 512
  encoder_type: 'cnn' # 'mlp' or 'cnn'
  encoder_output: [8, 32, 96]
  decoder_output: [128, 512, 3]
  gaze_output: '2d'

  # Preprocessing configuration.
  fourier_transform: false
  fourier_transform_params:
    trainable: true
    mapping_size: 256
    scale: 1

# Configuration for the loss function.
loss:
  functions: 'mse'
  metrics: 'mae'
