datasets:
  MPIIFaceGaze:
    path: "data/MPIIFaceGaze"
    train_subjects: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    val_subjects: [11, 12, 13, 14]
  GazeCapture:
    path: "data/GazeCapture"
train:
  train_size: 0.8
  batch_size: 32
  max_epoch: 100