datasets:
  MPIIFaceGaze:
    path: "data/MPIIFaceGaze"
train:

  # Model-Agnostic parameters
  train_size: 0.8
  batch_size: 2
  max_epochs: 20

  # Model specific parameters
  model_specific:
    EFE:
      hparams:
        heatmap_coef: 100.0
        xy_heatmap_loss: 10
        xy_loss: 10
        z_loss: 1
        angular_loss: 1
        pog_loss: 0.001
      dataset_params:
        # img_size: [640, 480]
        img_size: [244, 244]
        face_size: [244, 244]
    Gaze360:
      dataset_params:
        img_size: [640, 480]
        face_size: [244, 244]
    EyeTrack:
      hparams:
        angular_loss: 1
      dataset_params:
        img_size: [244, 244]
        face_size: [244, 244]