# Description: Configuration file for the GazeCapture dataset.
config:
  type: "autoencoder"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'EyeDiap'
  shuffle_buffer: 500
  seed: 42
  weighted: true

  train_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  val_ids: [10, 11]
  test_ids: [14, 15]

# Configuration for the optimizer.
optimizer:
  learning_rate: 0.001
  decay_rate: 0.95

# Training configuration.
training:
  epochs: 50
  batch_size: 8

  losses:
    RECONT_COEF: 1.0
    CONSISTENCY_COEF: 0.2
    GAZE_COEF: 1.0

# Configuration for the model.
model:
  mode: 'autoencoder'
  weights_fp: ""
  
  # Encoder configuration.
  encoder:
    input_shape: [128,512,3]
    embedding_size: 512

  decoder:
    input_shape: [8, 32, 96]

  # Gaze Estimation configuration.
  gaze:
    inputs:
      - name: 'head_vector'
        input_shape: [3]
      - name: 'face_origin_3d'
        input_shape: [3]
