# Description: Configuration file for the GazeCapture dataset.
config:
  type: "autoencoder"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'GazeCapture'
  seed: 42
  train_val_test_split: [0.8, 0.1]
  gazecapture:
    num_of_ids: 1000 # -1 means all ids
    max_per_participant: 25 # 32

# Configuration for the optimizer.
optimizer:
  learning_rate: 0.001
  decay_rate: 0.95

# Training configuration.
training:
  batch_size: 8
  epochs: 20
  num_of_workers: 4

# Configuration for the model.
model:
  mode: 'autoencoder'
  weights_fp: ""
  
  # Encoder configuration.
  encoder:
    input_shape: [128,512,3]
    embedding_size: 64

  decoder:
    input_shape: [8, 32, 96]

  # Gaze Estimation configuration.
  gaze:
    inputs:
      - name: 'cnn_output'
        input_shape: [64]
      - name: 'head_vector'
        input_shape: [3]
      - name: 'face_origin_3d'
        input_shape: [3]

# Configuration for the loss function.
loss:
  functions: 'mse'
  metrics: 'mae'

# Configuration for the callbacks.
callbacks:
  - 'TensorBoard'
  - 'ImageVisCallback'
  - 'EncoderDecoderCheckpoint'
