# Description: Configuration file for the GazeCapture dataset.
config:
  type: "maml"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'GazeCapture'
  seed: 42
  train_val_test_split: [0.8, 0.1]
  query_size: 100
  support_size: 9
  gazecapture:
    num_of_ids: -1 # -1 means all ids
    max_per_participant: 25 # 32

# Configuration for the optimizer.
optimizer:
  outer_lr: 0.0001 # 1e-4
  inner_lr: 0.00001 # 1e-5
  decay_rate: 0.95

# Training configuration.
training:
  batch_size: 8
  # num_outer_steps: 1000
  num_outer_steps: 500
  num_inner_steps: 5

# Configuration for the model.
model:
  mode: 'maml'
  # weights_fp: "2025-06-02-20-57-58_gazecapture_full_run_autoencoder"
  weights_fp: "2025-06-10-17-04-00_gazecapture_full_run_restart"
  
  # Encoder configuration.
  encoder:
    input_shape: [128,512,3]
    embedding_size: 512

  decoder:
    input_shape: [8, 32, 96]

  # Gaze Estimation configuration.
  gaze:
    inputs:
      - name: 'head_vector'
        input_shape: [3]
      - name: 'face_origin_3d'
        input_shape: [3]
