# Description: Configuration file for the GazeCapture dataset.
config:
  type: "maml"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'MPIIFaceGaze'
  seed: 42
  query_size: 100
  support_size: 9

  train_ids: [0]
  val_ids: [0]
  test_ids: [0]

# Configuration for the optimizer.
optimizer:
  outer_lr: 0.001 # 1e-3
  inner_lr: 0.00001 # 1e-5
  decay_rate: 0.95

# Training configuration.
training:
  batch_size: 8
  num_outer_steps: 5
  num_inner_steps: 100

# Configuration for the model.
model:
  mode: 'maml'
  weights_fp: "2025-06-01-21-26-25_mpiifacegaze_full_run_autoencoder"
  
  # Encoder configuration.
  encoder:
    input_shape: [128,512,3]
    embedding_size: 512

  decoder:
    input_shape: [8, 32, 96]

  # Gaze Estimation configuration.
  gaze:
    inputs:
      - name: 'head_vector'
        input_shape: [3]
      - name: 'face_origin_3d'
        input_shape: [3]
