# Description: Configuration file for the Eye of The Typer dataset.
config:
  type: "eye_of_the_typer"

visualize: False

calibration: True
steps_inner: 5
inner_lr: 0.00001 # 1e-5
affine_transform: True

preprocess:
  margin: 0.05

num_of_participants: 2