# Description: Configuration file for the GazeCapture dataset.
config:
  type: "autoencoder"

# Configuration file for the GazeCapture dataset.
dataset:
  name: 'MPIIFaceGaze'
  shuffle_buffer: 100
  seed: 42

  # train_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  # val_ids: [10, 11, 12]
  # test_ids: [13, 14]
  train_ids: [0]
  val_ids: [0]
  test_ids: [0]

# Configuration for the optimizer.
optimizer:
  learning_rate: 0.001
  decay_rate: 0.95

# Training configuration.
training:
  epochs: 20
  batch_size: 8
  num_outer_steps: 1000
  num_inner_steps: 5

# Configuration for the model.
model:
  mode: 'autoencoder'
  weights_fp: ""
  
  # Encoder configuration.
  encoder:
    input_shape: [128,512,3]
    embedding_size: 64

  decoder:
    input_shape: [8, 32, 96]

  # Gaze Estimation configuration.
  gaze:
    inputs:
      - name: 'head_vector'
        input_shape: [3]
      - name: 'face_origin_3d'
        input_shape: [3]
